# This file was generated by GoReleaser. DO NOT EDIT.
class MqttMirror < Formula
  desc "Replicate MQTT traffic from one broker to another."
  homepage "https://github.com/4nte/mqtt-mirror"
  version "0.1.7"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/4nte/mqtt-mirror/releases/download/v0.1.7/mqtt-mirror_0.1.7_Darwin_x86_64.tar.gz"
    sha256 "f93c8b48db80b3347443db210fb67a95403bb0a29b548578948b399c30b137e2"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/4nte/mqtt-mirror/releases/download/v0.1.7/mqtt-mirror_0.1.7_Linux_x86_64.tar.gz"
      sha256 "4dca046bc08fe7ebd0828b4efaed095e012bc1ebe1725b215c5eea9b2dc2f14a"
    end
  end

  def install
    bin.install "mqtt-mirror"
  end
end
