# This file was generated by GoReleaser. DO NOT EDIT.
class MqttMirror < Formula
  desc "Replicate MQTT traffic from one broker to another."
  homepage "https://github.com/4nte/mqtt-mirror"
  version "0.1.28"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/4nte/mqtt-mirror/releases/download/v0.1.28/mqtt-mirror_0.1.28_Darwin_x86_64.tar.gz"
    sha256 "1b89a048aa43087c62a80e71f7c25970d6e4a65e3ce6d61a325a5c0d59942f14"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/4nte/mqtt-mirror/releases/download/v0.1.28/mqtt-mirror_0.1.28_Linux_x86_64.tar.gz"
      sha256 "b1b722a810eade169b6aabea9528275496502d9b0f6a331d18be278dd5be85f3"
    end
  end

  def install
    bin.install "mqtt-mirror"
  end
end
